# Site settings
title: BigStash Developers Resources
email: team@bigstash.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/bigstash-dev" # the subpath of your site, e.g. /blog/
url: "http://longaccess.github.io/" # the base hostname & protocol for your site
twitter_username: BigStashHQ
github_username:  longaccess

# Build settings
markdown: kramdown
