# Site settings
title: BigStash Developers Resources
email: team@bigstash.co
description: > # this means to ignore newlines until "baseurl:"
  BigStash is a cloud-based archiving service. It’s built on top 
  of AWS Glacier and AWS S3, but hides the technical and billing 
  complexities of these services behind an easy to use interface 
  and simple pricing.
baseurl: "/bigstash-dev" # the subpath of your site, e.g. /blog/
url: "http://longaccess.github.io/" # the base hostname & protocol for your site
twitter_username: BigStashHQ
github_username:  longaccess

# Build settings
markdown: kramdown
